# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maciej/Dokumenty/wts

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maciej/Dokumenty/wts

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maciej/Dokumenty/wts/CMakeFiles /home/maciej/Dokumenty/wts//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maciej/Dokumenty/wts/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wts

# Build rule for target.
wts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wts
.PHONY : wts

# fast build rule for target.
wts/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/build
.PHONY : wts/fast

src/area.o: src/area.cpp.o
.PHONY : src/area.o

# target to build an object file
src/area.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/area.cpp.o
.PHONY : src/area.cpp.o

src/area.i: src/area.cpp.i
.PHONY : src/area.i

# target to preprocess a source file
src/area.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/area.cpp.i
.PHONY : src/area.cpp.i

src/area.s: src/area.cpp.s
.PHONY : src/area.s

# target to generate assembly for a file
src/area.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/area.cpp.s
.PHONY : src/area.cpp.s

src/battle.o: src/battle.cpp.o
.PHONY : src/battle.o

# target to build an object file
src/battle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/battle.cpp.o
.PHONY : src/battle.cpp.o

src/battle.i: src/battle.cpp.i
.PHONY : src/battle.i

# target to preprocess a source file
src/battle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/battle.cpp.i
.PHONY : src/battle.cpp.i

src/battle.s: src/battle.cpp.s
.PHONY : src/battle.s

# target to generate assembly for a file
src/battle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/battle.cpp.s
.PHONY : src/battle.cpp.s

src/field.o: src/field.cpp.o
.PHONY : src/field.o

# target to build an object file
src/field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/field.cpp.o
.PHONY : src/field.cpp.o

src/field.i: src/field.cpp.i
.PHONY : src/field.i

# target to preprocess a source file
src/field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/field.cpp.i
.PHONY : src/field.cpp.i

src/field.s: src/field.cpp.s
.PHONY : src/field.s

# target to generate assembly for a file
src/field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/field.cpp.s
.PHONY : src/field.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mapeditor.o: src/mapeditor.cpp.o
.PHONY : src/mapeditor.o

# target to build an object file
src/mapeditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/mapeditor.cpp.o
.PHONY : src/mapeditor.cpp.o

src/mapeditor.i: src/mapeditor.cpp.i
.PHONY : src/mapeditor.i

# target to preprocess a source file
src/mapeditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/mapeditor.cpp.i
.PHONY : src/mapeditor.cpp.i

src/mapeditor.s: src/mapeditor.cpp.s
.PHONY : src/mapeditor.s

# target to generate assembly for a file
src/mapeditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/mapeditor.cpp.s
.PHONY : src/mapeditor.cpp.s

src/theatrecontroller.o: src/theatrecontroller.cpp.o
.PHONY : src/theatrecontroller.o

# target to build an object file
src/theatrecontroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/theatrecontroller.cpp.o
.PHONY : src/theatrecontroller.cpp.o

src/theatrecontroller.i: src/theatrecontroller.cpp.i
.PHONY : src/theatrecontroller.i

# target to preprocess a source file
src/theatrecontroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/theatrecontroller.cpp.i
.PHONY : src/theatrecontroller.cpp.i

src/theatrecontroller.s: src/theatrecontroller.cpp.s
.PHONY : src/theatrecontroller.s

# target to generate assembly for a file
src/theatrecontroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/theatrecontroller.cpp.s
.PHONY : src/theatrecontroller.cpp.s

src/units.o: src/units.cpp.o
.PHONY : src/units.o

# target to build an object file
src/units.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/units.cpp.o
.PHONY : src/units.cpp.o

src/units.i: src/units.cpp.i
.PHONY : src/units.i

# target to preprocess a source file
src/units.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/units.cpp.i
.PHONY : src/units.cpp.i

src/units.s: src/units.cpp.s
.PHONY : src/units.s

# target to generate assembly for a file
src/units.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wts.dir/build.make CMakeFiles/wts.dir/src/units.cpp.s
.PHONY : src/units.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wts"
	@echo "... src/area.o"
	@echo "... src/area.i"
	@echo "... src/area.s"
	@echo "... src/battle.o"
	@echo "... src/battle.i"
	@echo "... src/battle.s"
	@echo "... src/field.o"
	@echo "... src/field.i"
	@echo "... src/field.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mapeditor.o"
	@echo "... src/mapeditor.i"
	@echo "... src/mapeditor.s"
	@echo "... src/theatrecontroller.o"
	@echo "... src/theatrecontroller.i"
	@echo "... src/theatrecontroller.s"
	@echo "... src/units.o"
	@echo "... src/units.i"
	@echo "... src/units.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

